image: gcc:10

pipelines:
  default:
    - step:
        script:
          - autoreconf -i
          - CFLAGS="-fsanitize=address" ./configure --enable-debug
          - make check
          - make distcheck
