image: gcc:6.1

pipelines:
  default:
    - step:
        script:
          - autoreconf -i
          - CFLAGS="-fsanitize=address" ./configure --enable-debug
          - make
          - make distcheck
